### ISSUE TITLE
Entregar full de renúncia

### ISSUE THREAD

**Issue by ssabate** [IESEBRE/2nDAM_21_22_Teacher_Tasks#14]
Alumnes que no volen començar l'FCT a l'octubre i han de presentar el full sol·licitant-ho.

Ompliu el document adjunt i penjeu-lo aquí mateix (si es pot). 
Aviseu-me de que ho heu fet posant-me una menció.
Si cal modifiqueu el text ja que lo vostre no és una renúncia sinó un aplaçament.
Indiqueu exactament la data de disponibilitat (no poseu coses com _quan aprove la UF4_, sinó, _a partir de gener_, per exemple)

@aormazaba @jordirp @Jhon1348 

[PGQC002-D02_Renuncia_a_cursar_la_FCT.docx](https://github.com/IESEBRE/2nDAM_21_22_Teacher_Tasks/files/7284922/PGQC002-D02_Renuncia_a_cursar_la_FCT.docx)

**Comment by aormazaba** [comment]
[PGQC002-D02_Renuncia_a_cursar_la_FCT.pdf](https://github.com/IESEBRE/2nDAM_21_22_Teacher_Tasks/files/7292031/PGQC002-D02_Renuncia_a_cursar_la_FCT.pdf)

**Comment by ssabate** [comment]
Albert, no cal que ho toques, però que sàpigues que el proper curs és el 22-23 ;-)
Gràcies!!
@aormazaba

**Comment by Jhon1348** [comment]
[PGQC002-D02_Renuncia_a_cursar_la_FCT_JDMG.pdf](https://github.com/IESEBRE/2nDAM_21_22_Teacher_Tasks/files/7293194/PGQC002-D02_Renuncia_a_cursar_la_FCT_JDMG.pdf)

@ssabate

**Comment by ssabate** [comment]
Perfecte, gràcies!!

@Jhon1348

**Comment by jordirp** [comment]
Missatge de Santi Sabaté ***@***.***> del dia dc., 6 d’oct.
2021 a les 15:24:

**Comment by jordirp** [comment]
[JordiRodriguez_PGQC002-D02_Renuncia_a_cursar_la_FCT.pdf](https://github.com/IESEBRE/2nDAM_21_22_Teacher_Tasks/files/7294735/JordiRodriguez_PGQC002-D02_Renuncia_a_cursar_la_FCT.pdf)

**Comment by ssabate** [comment]
Tot entregat

**Comment by ssabate** [comment]
Ompli el doc de dalt i penja'l aquí mateix @crystofol

**Comment by crystofol** [comment]
[CristianMurria_Renuncia_a_cursar_la_FCT.pdf](https://github.com/IESEBRE/2nDAM_21_22_Teacher_Tasks/files/7312535/CristianMurria_Renuncia_a_cursar_la_FCT.pdf)

**Comment by ssabate** [comment]
Fet @crystofol
