### ISSUE TITLE
Entrega de l’acta de constitució de l’equip (entrega #1)

### ISSUE THREAD

**Issue by ssabate** [IESEBRE/2nDAM_21_22_Teacher_Tasks#6]
Short description:

Entrega de l’acta de constitució de l’equip (entrega nº1)

Type:
- [x]  Equip 1
- [x]  Equip 2
- [x]  Equip 3

Estimated achievement date:

27/09/2021

**Comment by AvanteCaballe** [comment]
Ja hem penjat el nostre fitxer.

**Comment by ssabate** [comment]
> Ja hem penjat el nostre fitxer.

A quin repositori @IESEBRE/projecte-dam-21-22-3 ?

**Comment by AvanteCaballe** [comment]
> > Ja hem penjat el nostre fitxer.
> 
> A quin repositori @IESEBRE/projecte-dam-21-22-3 ?

No, aquí:
https://github.com/IESEBRE/projecte-dam-v2-equip3

**Comment by Jhon1348** [comment]
> Short description:
> 
> Entrega de l’acta de constitució de l’equip (entrega nº1)
> 
> Type:
> 
>     * [ ]   Equip 1
> 
>     * [x]   Equip 2
> 
>     * [x]   Equip 3
> 
> 
> Estimated achievement date:
> 
> 27/09/2021

**Comment by ssabate** [comment]
Provo si se tanca...
